global:
  resolve_timeout: 5m

route:
  receiver: telegram
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1m

receivers:
- name: telegram
  telegram_configs:
  - bot_token: 'token id'
    chat_id: chat_id
    send_resolved: true
    parse_mode: 'Markdown'